name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: miguelhermar/ai-code-reviewer@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}